swagger: '2.0'
info:
  version: 1.0.0
  title: Gea Login Page
  description: Login to GEA services to continue

paths:
  /Gea_Login:
    post:
      summary: Login to GEA services to continue
      description: Please provide your credentials to log in to GEA services.
      parameters:
        - name: username
          in: formData
          description: The username for login
          required: true
          type: string
        - name: password
          in: formData
          description: The password for login
          required: true
          type: string
   
